### ISSUE TITLE
Question about .NET Core

### ISSUE THREAD

**Issue by david-lorenzo88** [capslocky/WcfSoapLogger#16]
Hello,

Would it be possible to make this package compatible for .NET Core 2.0+ ?

Thank you
Best Regards
David

**Comment by capslocky** [comment]
Hi David,

As for now .NET Core provides only [client-side](https://github.com/dotnet/wcf) WCF library. And it seems to me it is possible to copy solution folder, adjust and compile targeting .NET Core, so you would be able to intercept outgoing soap requests.

Unfortunately I don't have time to check and release it by myself now.

May be you can try to do it?

**Comment by david-lorenzo88** [comment]
OK, I don't have to much time right now, but I will let you know if I finally have time to get it working.
Thank you
Best regards
David

**Comment by levinor** [comment]
Hi!
I understand this feature was never released, right?
Thx

**Comment by capslocky** [comment]
Unfortunately, there is no .NET Core version right now.
