### ISSUE TITLE
Consider moving to behavior instead of binding?

### ISSUE THREAD

**Issue by vanrace** [capslocky/WcfSoapLogger#21]
I am not able to use this extension since I already have a message encoding element on my customBinding defined (<textMessageEncoding messageVersion="Soap11" />), and .NET only supports one:

System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Cannot add the message encoding element 'soapLoggerMessageEncoding'. Another message encoding element already exists in the binding 

I think behaviors can always be combined?

Nice work btw!

**Comment by capslocky** [comment]
You see, we can't combine 2 message encodings in config, and we can't operate behavior here. But there is probable solution: create new message encoding to combine them.
Thank you!

**Comment by capslocky** [comment]
Feel free to ask for any further help.

**Comment by vanrace** [comment]
okay thanks
