### ISSUE TITLE
UTF-8 Error

### ISSUE THREAD

**Issue by ihocan** [capslocky/WcfSoapLogger#25]
Hello,
After We implement your solution to our project, our encoding broke, It's not working UTF-8 because of that we don't send any specail charecter 
could you help us?

**Comment by capslocky** [comment]
Hello,
Seems strange, because UTF-8 is a default encoding.
I used this library for intercepting special French characters with no problems.
Could you please clarify what are you doing and what is failing?

**Comment by ihocan** [comment]
We are using WcfSoapLogger for log service request and response (as default with UTF8 encoding).
But it has been change from WcfSoapLogger with UTF16 encoding.
We need to use Turkish Letters, such as "ğ,Ğ,ş,Ş,İ... etc." If we can set Encoding type as UTF8, we hope everything will be work fine. But now, our letters converting as unknown (?).

![resim](https://user-images.githubusercontent.com/6352894/50400752-3a8a2200-079a-11e9-8c10-72446265a4d4.png)

How can we set specific encoding type for our log request. We kindly request please share according code lines with us.

**Comment by capslocky** [comment]
As far as I understand, your web-service operates OK, but the problem only in corrupted log files.
Please try setting **saveOriginalBinaryBody="true"**, example is [here](https://github.com/capslocky/WcfSoapLogger/blob/master/src/UsageExamples/ExampleBeta/Service/App.config), so library wouldn't try to format XML and will save it as is. But last nuget release was before I have introduced it, so you need to compile WcfSoapLogger.dll from project source code and put it in your application.

Did it help?

**Comment by ihocan** [comment]
Our webservice encoding wrong too. It's not only log side. 
For example: We are using Name,Surname ..etc parameters on service method. When we use WcfSoapLogger encoding format changing and fields converting as Ayşe -> Ay?e , İhsan->?hsan, Büşra -> B??ra etc.

**Comment by capslocky** [comment]
I have a guess, please reach me in skype atanov.b.
